#指定应用名称
spring:
  application:
    name: market-system

#开启dao层的日志
logging:
  level:
    com:
      cfh:
        practice:
          dao: debug

#配置数据源
datasource:
   url: jdbc:mysql://localhost:3306/springboot?useSSL=false
   username: root
   password: 19981002520qq
   driver-class-name: com.mysql.jdbc.Driver
   # 使用druid数据源
   type: com.alibaba.druid.pool.DruidDataSource


#mybatis相关配置,mapperLocations指的路径是src/main/resources
mybatis:
  typeAliasesPackage: com.cfh.paractice.market.pojo
  mapperLocations: classpath:mappers/*.xml
