package com.cfh.practice.searchengine.dao;

import com.cfh.practice.searchengine.pojo.Tv;

import java.util.List;

public interface TvMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tv
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tv
     *
     * @mbggenerated
     */
    int insert(Tv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tv
     *
     * @mbggenerated
     */
    int insertSelective(Tv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tv
     *
     * @mbggenerated
     */
    Tv selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tv
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Tv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tv
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Tv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tv
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Tv record);

    List<Tv> flushDataSource();
}